# Site settings
title: Appboy Documentation
email: success@appboy.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Appboy Documentation. Appboy provides a comprehensive user engagement solution for your mobile apps.
baseurl: '' # the subpath of your site, e.g. /blog/
url: "https://documentation.appboy.com" # the base hostname & protocol for your site
twitter_username: Appboy
github_username:  Appboy
permalink: /:title/

# Pages directory
include: ["_pages"]

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  use_coderay: true # code highlighting
  coderay:
    coderay_line_numbers: nil
    coderay_css: class


# Collections
collections:
  Partner_Integrations:
    relative_directory: _collections/Partner_Integrations
  REST_API:
    relative_directory: _collections/REST_API
  Platform-Wide:
    relative_directory: _collections/Platform-Wide
  iOS:
    relative_directory: _collections/iOS
  Android_and_FireOS:
    relative_directory: _collections/Android_and_FireOS
  Windows:
    relative_directory: _collections/Windows
  Xamarin:
    relative_directory: _collections/Xamarin
  Unity:
    relative_directory: _collections/Unity
  Web:
    relative_directory: _collections/Web
